FROM php:8.2-apache
# mise à jour et installation des extensions php nécéssaires
RUN apt-get update \
    && apt-get install -y zlib1g-dev g++ git libicu-dev zip libzip-dev zip \
    && docker-php-ext-install intl opcache pdo pdo_mysql \
    && pecl install apcu \
    && docker-php-ext-enable apcu \
    && docker-php-ext-configure zip \
    && docker-php-ext-install zip
#activation du mode de réécriture de l'URL
RUN a2enmod rewrite && a2enmod ssl && a2enmod socache_shmcb

# dossier du projet en local
WORKDIR /var/www

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN curl -sS https://get.symfony.com/cli/installer | bash
RUN mv /root/.symfony5/bin/symfony /usr/local/bin/symfony

RUN git config --global user.email "briare-nguyen-outlook.fr"
RUN git config --global user.name "briare-ng"